"""initial

Revision ID: 34dc7a04bd4d
Revises: 
Create Date: 2026-08-18 12:14:38.805389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34dc7a04bd4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('registros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('num_patrimonio', sa.String(), nullable=False),
    sa.Column('setor', sa.String(), nullable=False),
    sa.Column('local_especifico', sa.String(), nullable=False),
    sa.Column('tipo_maquina', sa.Enum('MASTER', 'SLIM', name='tipo_maquina_enum'), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('registrado_por_id', sa.UUID(), nullable=False),
    sa.Column('registrado_em_dispositivo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_id'), 'registros', ['id'], unique=False)
    op.create_index(op.f('ix_registros_num_patrimonio'), 'registros', ['num_patrimonio'], unique=True)
    op.create_index(op.f('ix_registros_sincronizado_em'), 'registros', ['sincronizado_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_sincronizado_em'), table_name='registros')
    op.drop_index(op.f('ix_registros_num_patrimonio'), table_name='registros')
    op.drop_index(op.f('ix_registros_id'), table_name='registros')
    op.drop_table('registros')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
